version: '3.8'

services:
  # RAG应用服务
  rag-app:
    image: purui7/audio-app:1.0
    container_name: audio-app
    restart: always
    ports:
      - "15012:15012"
    environment:
      - TZ=Asia/Shanghai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge